eval_ckpt: /home/justin/Desktop/Code/sudoku-rl/guided_discrete/logs/mlm_test/2024-10-17_12-20-19/models/best_by_valid_0/epoch=439-step=14080.ckpt
num_eval_samples: 128
infill_dataset: satnet 
is_eval: True   
return_best: False # determines whether to return the highest value scoring trajectory across all diffusion timesteps
return_best_logits: False, #determines whether to return the highest value hidden among the guidance steps 
stability_coef: 0.01
add_guidance: False  
num_guidance_steps: 25


