defaults:
  - model: mlm

seed: ${trial_id}
trial_id: 0
project_name: guided_seq

data_dir: /home/justin/Desktop/Code/sudoku-rl/guided_discrete/data
#/scratch/nvg7279/datasets/sabdab_and_poas
train_fn: train_*.csv 
val_fn: val_iid.csv
#train: larger_satnet
#valid: larger_satnet
#train: rrn
#valid: rrn
max_samples: 100000
infill_dataset: rrn 

target_cols: null 
discr_batch_ratio: null

vocab_file: /home/justin/Desktop/Code/sudoku-rl/guided_discrete/vocab.txt 
vocab_size: 30
use_alignment_tokens: True

log_dir: /home/justin/Desktop/Code/sudoku-rl/guided_discrete/logs 
exp_name: nos_test
exp_dir: ${log_dir}/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}

val_sample_frequency: 5
num_samples: 16
num_solutions_generate: 1 #10 
infill_seeds_fn: null #/home/nvg7279/src/seq-struct/infill_test_seeds.txt
guidance_kwargs: null
autoregressive_sample: False

resume_ckpt: null
#/scratch/nvg7279/logs/guided_protein_seq/var_length_test/models/best_by_valid/epoch=1-step=134.ckpt 
#/scratch/nvg7279/logs/guided_protein_seq/test/models/best_by_valid/epoch=9-step=790.ckpt

max_seq_len: 300
min_seq_len: 128
trim_strategy: "randomcrop"

gradient_clip: 10.0
min_epochs: 1000
max_epochs: 1000
early_stop_patience: 0
batch_size: 128
loader_workers: 4

ngpu: 1

use_wandb: false 

hydra:
  run:
    dir: ${exp_dir}
  sweep:
    dir: ${exp_dir}